//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSBM_RestaurantMGR.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSBM_RestaurantMGR.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        internal static string BillingForm_Drinks {
            get {
                return ResourceManager.GetString("BillingForm_Drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras:.
        /// </summary>
        internal static string BillingForm_Extras {
            get {
                return ResourceManager.GetString("BillingForm_Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Bill.
        /// </summary>
        internal static string BillingForm_GenerateBill {
            get {
                return ResourceManager.GetString("BillingForm_GenerateBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Bill:.
        /// </summary>
        internal static string BillingForm_Header {
            get {
                return ResourceManager.GetString("BillingForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info:.
        /// </summary>
        internal static string BillingForm_Info {
            get {
                return ResourceManager.GetString("BillingForm_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of People:.
        /// </summary>
        internal static string BillingForm_NumberOfPeople {
            get {
                return ResourceManager.GetString("BillingForm_NumberOfPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment:.
        /// </summary>
        internal static string BillingForm_Payment {
            get {
                return ResourceManager.GetString("BillingForm_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method:.
        /// </summary>
        internal static string BillingForm_PaymentMethod {
            get {
                return ResourceManager.GetString("BillingForm_PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Meat.
        /// </summary>
        internal static string BillingForm_PremiumMeat {
            get {
                return ResourceManager.GetString("BillingForm_PremiumMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per Person:.
        /// </summary>
        internal static string BillingForm_PricePerPerson {
            get {
                return ResourceManager.GetString("BillingForm_PricePerPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing:.
        /// </summary>
        internal static string BillingForm_Pricing {
            get {
                return ResourceManager.GetString("BillingForm_Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal:.
        /// </summary>
        internal static string BillingForm_Subtotal {
            get {
                return ResourceManager.GetString("BillingForm_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table:.
        /// </summary>
        internal static string BillingForm_Table {
            get {
                return ResourceManager.GetString("BillingForm_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Info:.
        /// </summary>
        internal static string BillingForm_TableInfo {
            get {
                return ResourceManager.GetString("BillingForm_TableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip (%):.
        /// </summary>
        internal static string BillingForm_Tip {
            get {
                return ResourceManager.GetString("BillingForm_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing MGR.
        /// </summary>
        internal static string BillingForm_Title {
            get {
                return ResourceManager.GetString("BillingForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string BillingForm_Total {
            get {
                return ResourceManager.GetString("BillingForm_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string MainForm_Billing {
            get {
                return ResourceManager.GetString("MainForm_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Manager System.
        /// </summary>
        internal static string MainForm_Header {
            get {
                return ResourceManager.GetString("MainForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string MainForm_Language {
            get {
                return ResourceManager.GetString("MainForm_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MainForm_No {
            get {
                return ResourceManager.GetString("MainForm_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string MainForm_Quit {
            get {
                return ResourceManager.GetString("MainForm_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        internal static string MainForm_QuitConfirmation {
            get {
                return ResourceManager.GetString("MainForm_QuitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        internal static string MainForm_Reservations {
            get {
                return ResourceManager.GetString("MainForm_Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string MainForm_Tables {
            get {
                return ResourceManager.GetString("MainForm_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestoMGR.
        /// </summary>
        internal static string MainForm_Title {
            get {
                return ResourceManager.GetString("MainForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MainForm_Yes {
            get {
                return ResourceManager.GetString("MainForm_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this reservation?.
        /// </summary>
        internal static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string Message_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes were made.
        /// </summary>
        internal static string Message_NoChangesMade {
            get {
                return ResourceManager.GetString("Message_NoChangesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation added successfully..
        /// </summary>
        internal static string Message_ReservationAdded {
            get {
                return ResourceManager.GetString("Message_ReservationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation deleted..
        /// </summary>
        internal static string Message_ReservationDeleted {
            get {
                return ResourceManager.GetString("Message_ReservationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation updated successfully..
        /// </summary>
        internal static string Message_ReservationUpdated {
            get {
                return ResourceManager.GetString("Message_ReservationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a reservation..
        /// </summary>
        internal static string Message_SelectReservation {
            get {
                return ResourceManager.GetString("Message_SelectReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a table..
        /// </summary>
        internal static string Message_SelectTable {
            get {
                return ResourceManager.GetString("Message_SelectTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a table status and type..
        /// </summary>
        internal static string Message_SelectTableOptions {
            get {
                return ResourceManager.GetString("Message_SelectTableOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load tables..
        /// </summary>
        internal static string Message_TableLoadError {
            get {
                return ResourceManager.GetString("Message_TableLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table updated successfully..
        /// </summary>
        internal static string Message_TableUpdated {
            get {
                return ResourceManager.GetString("Message_TableUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update table..
        /// </summary>
        internal static string Message_TableUpdateError {
            get {
                return ResourceManager.GetString("Message_TableUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reservation.
        /// </summary>
        internal static string ReservationForm_AddReservation {
            get {
                return ResourceManager.GetString("ReservationForm_AddReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ReservationForm_Clear {
            get {
                return ResourceManager.GetString("ReservationForm_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER INFO:.
        /// </summary>
        internal static string ReservationForm_CustomerInfo {
            get {
                return ResourceManager.GetString("ReservationForm_CustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name:.
        /// </summary>
        internal static string ReservationForm_CustomerName {
            get {
                return ResourceManager.GetString("ReservationForm_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string ReservationForm_Date {
            get {
                return ResourceManager.GetString("ReservationForm_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Reservation.
        /// </summary>
        internal static string ReservationForm_DeleteReservation {
            get {
                return ResourceManager.GetString("ReservationForm_DeleteReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reservation.
        /// </summary>
        internal static string ReservationForm_EditReservation {
            get {
                return ResourceManager.GetString("ReservationForm_EditReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Reservations:.
        /// </summary>
        internal static string ReservationForm_Header {
            get {
                return ResourceManager.GetString("ReservationForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Size:.
        /// </summary>
        internal static string ReservationForm_PartySize {
            get {
                return ResourceManager.GetString("ReservationForm_PartySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string ReservationForm_Phone {
            get {
                return ResourceManager.GetString("ReservationForm_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ReservationForm_Refresh {
            get {
                return ResourceManager.GetString("ReservationForm_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVATION DETAILS:.
        /// </summary>
        internal static string ReservationForm_ReservationDetails {
            get {
                return ResourceManager.GetString("ReservationForm_ReservationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (Name/ID):.
        /// </summary>
        internal static string ReservationForm_Search {
            get {
                return ResourceManager.GetString("ReservationForm_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Today&apos;s Reservations.
        /// </summary>
        internal static string ReservationForm_ShowToday {
            get {
                return ResourceManager.GetString("ReservationForm_ShowToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ReservationForm_Status {
            get {
                return ResourceManager.GetString("ReservationForm_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table:.
        /// </summary>
        internal static string ReservationForm_Table {
            get {
                return ResourceManager.GetString("ReservationForm_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string ReservationForm_Time {
            get {
                return ResourceManager.GetString("ReservationForm_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation MGR.
        /// </summary>
        internal static string ReservationForm_Title {
            get {
                return ResourceManager.GetString("ReservationForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Status_Cancelled {
            get {
                return ResourceManager.GetString("Status_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Status_Completed {
            get {
                return ResourceManager.GetString("Status_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string Status_Confirmed {
            get {
                return ResourceManager.GetString("Status_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-show.
        /// </summary>
        internal static string Status_NoShow {
            get {
                return ResourceManager.GetString("Status_NoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Status_Pending {
            get {
                return ResourceManager.GetString("Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seated.
        /// </summary>
        internal static string Status_Seated {
            get {
                return ResourceManager.GetString("Status_Seated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Table:.
        /// </summary>
        internal static string TableForm_EditTable {
            get {
                return ResourceManager.GetString("TableForm_EditTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Tables:.
        /// </summary>
        internal static string TableForm_Header {
            get {
                return ResourceManager.GetString("TableForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Table:.
        /// </summary>
        internal static string TableForm_SelectedTable {
            get {
                return ResourceManager.GetString("TableForm_SelectedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string TableForm_Status {
            get {
                return ResourceManager.GetString("TableForm_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table MGR.
        /// </summary>
        internal static string TableForm_Title {
            get {
                return ResourceManager.GetString("TableForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string TableForm_Type {
            get {
                return ResourceManager.GetString("TableForm_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Table.
        /// </summary>
        internal static string TableForm_UpdateTable {
            get {
                return ResourceManager.GetString("TableForm_UpdateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats.
        /// </summary>
        internal static string TableGrid_Capacity {
            get {
                return ResourceManager.GetString("TableGrid_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string TableGrid_Status {
            get {
                return ResourceManager.GetString("TableGrid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table #.
        /// </summary>
        internal static string TableGrid_TableNumber {
            get {
                return ResourceManager.GetString("TableGrid_TableNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean BBQ Table.
        /// </summary>
        internal static string TableGrid_TableType {
            get {
                return ResourceManager.GetString("TableGrid_TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string TableStatus_Available {
            get {
                return ResourceManager.GetString("TableStatus_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied.
        /// </summary>
        internal static string TableStatus_Occupied {
            get {
                return ResourceManager.GetString("TableStatus_Occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string TableStatus_Reserved {
            get {
                return ResourceManager.GetString("TableStatus_Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-seat party grill.
        /// </summary>
        internal static string TableType_EightSeat {
            get {
                return ResourceManager.GetString("TableType_EightSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-seat BBQ grill.
        /// </summary>
        internal static string TableType_FourSeat {
            get {
                return ResourceManager.GetString("TableType_FourSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-seat family grill.
        /// </summary>
        internal static string TableType_SixSeat {
            get {
                return ResourceManager.GetString("TableType_SixSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-seat BBQ grill.
        /// </summary>
        internal static string TableType_TwoSeat {
            get {
                return ResourceManager.GetString("TableType_TwoSeat", resourceCulture);
            }
        }
    }
}
